apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-jen-k8
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: p565656/dockerfilejen:latest
        ports:
        - containerPort: 8980

